# Generated by Django 3.1.7 on 2021-04-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Recipe Comment', 'verbose_name_plural': 'Recipe Comments'},
        ),
    ]
